### ISSUE TITLE
Compare functional scores to functional effects inferred from global epistasis model

### ISSUE THREAD

**Issue by Caleb-Carr** [dms-vep/LASV_Josiah_GP_DMS#12]
Create a correlation plot for single mutant variant scores and the deconvolved single mutant functional effects inferred from the global epistasis model.

**Comment by Caleb-Carr** [comment]
@jbloom This [notebook](https://dms-vep.org/LASV_Josiah_GP_DMS/notebooks/func_scores_vs_func_effects.html) compares the functional scores calculated for barcoded variants with single amino-acid mutations to the functional effects of mutations inferred from the global epistasis model. Overall, seems like scores are highly correlated.

**Comment by jbloom** [comment]
Yes

**Comment by Caleb-Carr** [comment]
@jbloom Updated [notebook](https://dms-vep.org/LASV_Josiah_GP_DMS/notebooks/func_scores_vs_func_effects.html):
- To show `times_seen` for both single mutant variants and all variants as a tooltips
- To show correlation subsetted on single mutants seen in >= 1 barcoded variants and >=2 barcoded variants
- To show the number of mutations measured with single mutant variants (7566 mutations). Will use to make table for mutations measured as single mutants and all mutations measured with multi-mutant variants

**Comment by jbloom** [comment]
Sounds good. For the paper I think we should probably add in the supplement the plot with the >= 2 times seen in single mutants, since that is the comparable threshold to what we use for times_seen for global epistasis fit models.
