### ISSUE TITLE
Compare DMS scores for each region as defined in Figure 2C to the natural variability (i.e., effective amino acids) for that region

### ISSUE THREAD

**Issue by Caleb-Carr** [dms-vep/LASV_Josiah_GP_DMS#13]
This issue is related to the following reviewer comment: 

**_1. The GP2 domains are more functionally constrained than GP1. How conserved are these epitopes among different Lassa lineages?_**

_It seems like they are basically asking for us to assess if GP2 is more constrained in terms of natural variation than GP1. Maybe you could analyze the relative variability (using number of effective amino acids averaged across sites) for each domain as defined in Figure 2C and see to what extent domain-level constraint from DMS corresponds to natural variability._

**Comment by Caleb-Carr** [comment]
@jbloom This [notebook](https://dms-vep.org/LASV_Josiah_GP_DMS/notebooks/func_effects_vs_natural_variation.html) analyzes the functional effects of mutations compared to natural variation (effective amino acids) at each site for different GPC regions. Note that this is site level analysis and the last plot differs from Figure 2C because mutation effects are averaged across each site to be consistent with the site level effective amino acid metric.

**Comment by jbloom** [comment]
OK, we will have to figure out what exactly to show to address reviewer comment. Comment is more about domains than all the other more fine-grained subsets of sites. Also, I wonder if site entropy would be better than effective amino acids since it won't collapse the smaller values and exaggerate the larger ones as much.

**Comment by Caleb-Carr** [comment]
@jbloom Updated [notebook](https://dms-vep.org/LASV_Josiah_GP_DMS/notebooks/func_effects_vs_natural_variation.html) to only show the three main domains of GPC (SSP, GP1, and GP2) and changed metric to site entropy. To more directly address the question of GP2 being more constrained than GP1, I did a Mann-Whitney U test for the site entropy between each of the regions.

**Comment by jbloom** [comment]
Looks good. Maybe make the points a bit darker or draw a thin black border (using stroke, strokeWidth in `altair`) as they are hard to see in current plots.

**Comment by Caleb-Carr** [comment]
Im closing this issue because the latest plot has points altered to be more visible
