### ISSUE TITLE
Plot distribution of functional effects stratified by times observed in natural GPC sequences 

### ISSUE THREAD

**Issue by Caleb-Carr** [dms-vep/LASV_Josiah_GP_DMS#14]
Make plots of the distribution of effects of: 
- all amino-acid mutations
- amino acid mutations observed at least once in a natural GPC
- amino acids mutations observed at least N times in a natural GPC, where you make some reasonable choice of N > 1.

This is related to the following comment: 

**_4. According to Figure 2C, most (perhaps more than 90%) of the single mutations on GPC are deleterious to viral entry. However, the GPC of different Lassa lineages seems to tolerate amino acid differences as high as ~10% (Figure 1C). The authors should provide possible explanations. Meanwhile, different Lassa lineages already have a sizeable antigenic diversity, so the application of the DMS map developed based on the Josiah strain to other lineages might be limited._**

**Comment by Caleb-Carr** [comment]
@jbloom This [notebook](https://dms-vep.org/LASV_Josiah_GP_DMS/notebooks/func_effects_of_naturally_present_mutations.html) plots the distributions of functional effects of mutations stratified by times observed in natural sequences.

**Comment by Caleb-Carr** [comment]
@jbloom Updated [notebook](https://dms-vep.org/LASV_Josiah_GP_DMS/notebooks/func_effects_of_naturally_present_mutations.html) to a more lenient top cutoff (>=10) and changed distributions to boxplots.

**Comment by jbloom** [comment]
Looks good.
