### ISSUE TITLE
Antibody escape vs functional effects plots to access potential of antibody escape

### ISSUE THREAD

**Issue by Caleb-Carr** [dms-vep/LASV_Josiah_GP_DMS#15]
This issue is related to the following comments:

_**Codon-optimized GPC was used for DMS analysis. The accessibility to specific aa mutations might differ between optimized DNA sequences and DNA sequences representing GPC on the viral genome.**_

_**Antibody escape mutations that are associated with little cost to GPC function seem like the most critical subset of mutations to focus on for future therapeutic design. Their identification is a major strength of this work, however, understanding the extent and identity of these is challenging from how they are represented in the figures (specifically, Fig 3B inset and Fig 4A). Could these be shown in a separate panel / figure rather than embedded into the already dense amino acid plots. For example, would plotting cell entry effect against site escape or some other direct comparison allow for these to be more clearly identified? This could be per antibody or potentially across all, with color or shape denoting antibody identity. This finding is central to the evolutionary capacity of Lassa GPC to escape antibodies but is not currently well demonstrated.**_

**Comment by Caleb-Carr** [comment]
@jbloom This [interactive plot](https://dms-vep.org/LASV_Josiah_GP_DMS/htmls/antibody_escape_vs_func_effect_all_muts.html) shows the relationship between functional effects and antibody escape. This plot is also colored by mutations that are only one nucleotide mutation away based on the Josiah nucleotide sequence (NC_004296). Static versions of this image are also created in this [notebook](https://dms-vep.org/LASV_Josiah_GP_DMS/notebooks/escape_vs_func_effects.html) for the paper.

**Comment by jbloom** [comment]
I forget the exact comment this is in response to, but my thoughts:
 - why is the range of cell entry effects from -1 to 1? Shouldn't there be many more mutations that are far worse for cell entry than -1? Also, if this is just to show constraint of epitope should the top be >= 0.
 - I think the plot would probably be better if the single-nt versus all mutations were faceted in two rows rather than overlaid, as things are hard to see.

**Comment by Caleb-Carr** [comment]
The reviewers comments related to this analysis is in the main issue post above.

- The antibody escape data is filtered at -1.5 functional effects but for this plot, I could show unfiltered antibody escape and maybe draw a dotted line at -1.5 to show that is where the data is filtered? 
- And faceted the plot by single-nt vs all sounds good!

**Comment by Caleb-Carr** [comment]
Im closing this issue because the latest plot is faceted by single-nt mutations and shows the functional effects from -1.5 to >=0
