### ISSUE TITLE
better link homepage to paper

### ISSUE THREAD

**Issue by jbloom** [dms-vep/LASV_Josiah_GP_DMS#16]
@Caleb-Carr, I was just looking at your LASV homepage at [https://dms-vep.org/LASV_Josiah_GP_DMS/](https://dms-vep.org/LASV_Josiah_GP_DMS/).

I do like how you have the "paper" box in the upper right, that is cool!

However, you should still do a better job of linking it to the actual paper. That is what describes the actual experiment, so we want it to be easy for people to find the paper.

Look at the H5 homepage ([https://dms-vep.org/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/](https://dms-vep.org/Flu_H5_American-Wigeon_South-Carolina_2021-H5N1_DMS/)). Have the front page link to something that looks like an actual citation (eg, _Carr, Crawford, et al (2024)_) not just an offhand reference to "this paper". And when you say who did the study, link that to the citation. Also, make the footer include the citation like for the H5 paper. Likewise for your _Experiments_ subpage: a link to your paper should be one of the most prominent things and should look like an actual author-date citation; it shouldn't be the minor note at the end of the whole subsection.

**Comment by Caleb-Carr** [comment]
I have updated the _Index_ page and _Experiments_ subpage to include links that look like actual citations as well as updated the footer to include a link to the paper. This 4611de0c4e834a75e99f57451f371a8af64ee953 commit made these changes.
